### PR TITLE
fixed record count to be an integer temporarily, until libtaxii is fi…

### PR DESCRIPTION
**Pull request by code040**
…xed and handles long as well

### CODE REVIEW

**Comment by traut** [comment]
could you please workaround for other 2 fields as well?

**Comment by code040** [comment]
@traut sorry that this was slacking. Which fields are you referring to?

**Comment by traut** [comment]
@code040 2 other from this issue - https://github.com/TAXIIProject/libtaxii/issues/191

**Comment by code040** [comment]
thanks!

**Pull request merged**
